### ISSUE TITLE
3d jiggle physics do not detected Secretary 

### ISSUE THREAD

**Issue by Prinzkc** [laplamgor/kantai3d#4]
Its happen on gotobrowser, whenever i try to to turn it , it Always say "Secretary do not detected" even when i use one of the list CG 

Please fix

**Comment by laplamgor** [comment]
it is currently broken and pending for a fix

在 2024年8月15日週四 上午12:04，Prinzkc ***@***.***> 寫道：

**Comment by laplamgor** [comment]
Should be working at the time of writing
